/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationStatus = IDL.Variant({
  'in_progress' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
  'received' : IDL.Null,
});
export const Time = IDL.Int;
export const VisaApplication = IDL.Record({
  'status' : ApplicationStatus,
  'dateOfBirth' : IDL.Text,
  'lastUpdated' : Time,
  'submissionDate' : Time,
  'passportNumber' : IDL.Text,
  'applicationType' : IDL.Text,
  'applicationReferenceNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getVisaApplication' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VisaApplication)],
      ['query'],
    ),
  'seedSampleApplications' : IDL.Func([], [], []),
  'submitVisaApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateApplicationStatus' : IDL.Func([IDL.Text, ApplicationStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationStatus = IDL.Variant({
    'in_progress' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
    'received' : IDL.Null,
  });
  const Time = IDL.Int;
  const VisaApplication = IDL.Record({
    'status' : ApplicationStatus,
    'dateOfBirth' : IDL.Text,
    'lastUpdated' : Time,
    'submissionDate' : Time,
    'passportNumber' : IDL.Text,
    'applicationType' : IDL.Text,
    'applicationReferenceNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getVisaApplication' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VisaApplication)],
        ['query'],
      ),
    'seedSampleApplications' : IDL.Func([], [], []),
    'submitVisaApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateApplicationStatus' : IDL.Func([IDL.Text, ApplicationStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };