/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VisaApplication {
    status: ApplicationStatus;
    dateOfBirth: string;
    lastUpdated: Time;
    submissionDate: Time;
    passportNumber: string;
    applicationType: string;
    applicationReferenceNumber: string;
}
export type Time = bigint;
export enum ApplicationStatus {
    in_progress = "in_progress",
    approved = "approved",
    declined = "declined",
    received = "received"
}
export interface backendInterface {
    getVisaApplication(referenceNumber: string): Promise<VisaApplication | null>;
    seedSampleApplications(): Promise<void>;
    submitVisaApplication(referenceNumber: string, passportNumber: string, dateOfBirth: string, applicationType: string): Promise<void>;
    updateApplicationStatus(referenceNumber: string, newStatus: ApplicationStatus): Promise<void>;
}
import type { ApplicationStatus as _ApplicationStatus, Time as _Time, VisaApplication as _VisaApplication } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getVisaApplication(arg0: string): Promise<VisaApplication | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisaApplication(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisaApplication(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedSampleApplications(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleApplications();
            return result;
        }
    }
    async submitVisaApplication(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVisaApplication(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVisaApplication(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateApplicationStatus(arg0: string, arg1: ApplicationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApplicationStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_VisaApplication_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisaApplication): VisaApplication {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VisaApplication]): VisaApplication | null {
    return value.length === 0 ? null : from_candid_VisaApplication_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApplicationStatus;
    dateOfBirth: string;
    lastUpdated: _Time;
    submissionDate: _Time;
    passportNumber: string;
    applicationType: string;
    applicationReferenceNumber: string;
}): {
    status: ApplicationStatus;
    dateOfBirth: string;
    lastUpdated: Time;
    submissionDate: Time;
    passportNumber: string;
    applicationType: string;
    applicationReferenceNumber: string;
} {
    return {
        status: from_candid_ApplicationStatus_n4(_uploadFile, _downloadFile, value.status),
        dateOfBirth: value.dateOfBirth,
        lastUpdated: value.lastUpdated,
        submissionDate: value.submissionDate,
        passportNumber: value.passportNumber,
        applicationType: value.applicationType,
        applicationReferenceNumber: value.applicationReferenceNumber
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    in_progress: null;
} | {
    approved: null;
} | {
    declined: null;
} | {
    received: null;
}): ApplicationStatus {
    return "in_progress" in value ? ApplicationStatus.in_progress : "approved" in value ? ApplicationStatus.approved : "declined" in value ? ApplicationStatus.declined : "received" in value ? ApplicationStatus.received : value;
}
function to_candid_ApplicationStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    in_progress: null;
} | {
    approved: null;
} | {
    declined: null;
} | {
    received: null;
} {
    return value == ApplicationStatus.in_progress ? {
        in_progress: null
    } : value == ApplicationStatus.approved ? {
        approved: null
    } : value == ApplicationStatus.declined ? {
        declined: null
    } : value == ApplicationStatus.received ? {
        received: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
